# Generated by Django 3.1.3 on 2020-11-19 03:57

import administration.utils.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('crm', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone no máximo 11 digitos', regex='^\\d{10,11}$')])),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.especialidade')),
            ],
            options={
                'verbose_name': 'Médico',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(validators=[administration.utils.validators.NoPast])),
                ('horarios', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), help_text='Insira os horários no formato Hora:Minuto separados por virgula', size=None, verbose_name='Horários')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.medico', verbose_name='Médico')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('medico', 'dia'), name='unique_doctor_schedule_by_day'),
        ),
    ]
