# Generated by Django 3.1.3 on 2020-11-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('crm', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.especialidade')),
            ],
        ),
    ]
