# Generated by Django 3.1.3 on 2020-11-17 09:58

import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_medico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico'},
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone no máximo 11 digitos', regex='^\\d{10,11}$')]),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(validators=[django.core.validators.MinLengthValidator(limit_value=datetime.date.today, message='O Dia não pode ser menor que hoje!')])),
                ('horarios', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.medico')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('medico', 'dia'), name='unique_doctor_schedule_by_day'),
        ),
    ]
